name: Go

on:
  push:

jobs:
  build-artifact:
    name: 'Test and Build Artifact'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v

    - name: Build
      run: go build -v -o output/build_artifact

    - name: Package Deploy Artifact
      working-directory: output
      run: zip deploy_artifact build_artifact

    - uses: actions/upload-artifact@v3
      working-directory: output
      with:
        name: deploy_artifact
        path: deploy_artifact

  deploy-infrastructure:
    name: 'Deploy Build Artifact and Infrastructure'
    needs: build-artifact
    uses: ./.github/workflows/deploy_infrastructure.yml
    with:
      environment: development
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}