name: Go

on:
  push:

jobs:
  build-artifact:
    name: 'Test and Build Artifact'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v

    - name: Build
      run: go build -v -o build_artifact.out

    - uses: actions/upload-artifact@v3
      with:
        name: build_artifact
        path: build_artifact.out

  deploy-infrastructure:
    name: 'Deploy Build Artifact and Infrastructure'
    needs: build-artifact
    runs-on: ubuntu-latest

    steps:
    - uses: ./.github/workflows/deploy_infrastructure.yml
      with:
        environment: development
      secrets:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}